version: "3.8"

services:
  web:
    build: .
    env_file:
      - .env
    ports:
      - 4000:4000
    volume:
      - .:/usr/src/app
    command: air run main.go -b 0.0.0.0
  db:
    image: postgres:alpine
    enviroment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_PASSWORD = ${DB_PASSWORD}
      - DB_USER={DB_USER}
      - DB_NAME={DB_NAME}
    ports:
      - 5432:5432
    volume:
      - postgres-db: /var/lib/postgresql/data

volumes:
  postgres-db:
